PlanillaBundle\Entity\ActProy:
    type: entity
    repositoryClass: PlanillaBundle\Repository\ActProyRepository
    table: act_proy
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        anoEje:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: ano_eje
        actProy:
            type: string
            nullable: false
            length: 10
            options:
                fixed: true
            column: act_proy
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: true
        esPresupu:
            type: boolean
            nullable: true
            column: es_presupu
    lifecycleCallbacks: {  }
