PlanillaBundle\Entity\Afp:
    type: entity
    table: afp
    id:
        id:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        regimenPensionario:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
            column: regimen_pensionario
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        estado:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
        snp:
            type: float
            nullable: true
            precision: 10
            scale: 0
        jubilacion:
            type: float
            nullable: true
            precision: 10
            scale: 0
        seguros:
            type: float
            nullable: true
            precision: 10
            scale: 0
        ra:
            type: float
            nullable: true
            precision: 10
            scale: 0
        pension:
            type: float
            nullable: true
            precision: 10
            scale: 0
        raMixta:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: ra_mixta
    lifecycleCallbacks: {  }
