PlanillaBundle\Entity\Afp:
    type: entity
    table: afp
    indexes:
        fk_afp_regimen_pensionario1_idx:
            columns:
                - regimen_pensionario
    id:
        id:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
        snp:
            type: float
            nullable: true
            precision: 10
            scale: 0
        jubilacion:
            type: float
            nullable: true
            precision: 10
            scale: 0
        seguros:
            type: float
            nullable: true
            precision: 10
            scale: 0
        ra:
            type: float
            nullable: true
            precision: 10
            scale: 0
        pension:
            type: float
            nullable: true
            precision: 10
            scale: 0
        raMixta:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: ra_mixta
    manyToOne:
        regimenPensionario:
            targetEntity: RegimenPensionario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                regimen_pensionario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
