PlanillaBundle\Entity\CategoriaOcupacional:
    type: entity
    repositoryClass: PlanillaBundle\Repository\CategoriaOcupacionalRepository
    table: categoria_ocupacional
    indexes:
        fk_categoria_ocupacional_grupo_ocupacional1_idx:
            columns:
                - grupo_ocupacional
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        categoriaOcupacional:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
            column: categoria_ocupacional
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
        abreviatura:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        grupoOcupacional:
            targetEntity: GrupoOcupacional
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                grupo_ocupacional:
                    referencedColumnName: grupo_ocupacional
            orphanRemoval: false
    lifecycleCallbacks: {  }
