PlanillaBundle\Entity\Concepto:
    type: entity
    table: concepto
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tipoConcepto:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
            column: tipo_concepto
        concepto:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        abreviatura:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        formaMonto:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: forma_monto
        estado:
            type: boolean
            nullable: true
        esActivo:
            type: boolean
            nullable: true
            column: es_activo
        esPension:
            type: boolean
            nullable: true
            column: es_pension
        esPatronal:
            type: boolean
            nullable: true
            column: es_patronal
        esAsegurada:
            type: boolean
            nullable: true
            column: es_asegurada
        esAfp:
            type: boolean
            nullable: true
            column: es_afp
        mcppConcepto:
            type: string
            nullable: true
            length: 4
            options:
                fixed: true
            column: mcpp_concepto
    lifecycleCallbacks: {  }
