PlanillaBundle\Entity\Concepto:
    type: entity
    repositoryClass: PlanillaBundle\Repository\ConceptoRepository
    table: concepto
    indexes:
        fk_concepto_tipo_concepto1_idx:
            columns:
                - tipo_concepto
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        concepto:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        abreviatura:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        formaMonto:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: forma_monto
        estado:
            type: boolean
            nullable: true
        esActivo:
            type: boolean
            nullable: true
            column: es_activo
        esPension:
            type: boolean
            nullable: true
            column: es_pension
        esPatronal:
            type: boolean
            nullable: true
            column: es_patronal
        esAsegurada:
            type: boolean
            nullable: true
            column: es_asegurada
        esAfp:
            type: boolean
            nullable: true
            column: es_afp
        mcppConcepto:
            type: string
            nullable: true
            length: 4
            options:
                fixed: true
            column: mcpp_concepto
    manyToOne:
        tipoConcepto:
            targetEntity: TipoConcepto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_concepto:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
