PlanillaBundle\Entity\CondicionLaboral:
    type: entity
    table: condicion_laboral
    id:
        id:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
