PlanillaBundle\Entity\Direcciones:
    type: entity
    table: direcciones
    id:
        codigo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: DIR
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        estado:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
