PlanillaBundle\Entity\Especifica:
    type: entity
    table: especifica
    id:
        anoEje:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ano_eje
        especifica:
            type: string
            nullable: false
            length: 10
            options:
                fixed: true
            id: true
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        estado:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
    lifecycleCallbacks: {  }
