PlanillaBundle\Entity\FuenteFinanc:
    type: entity
    table: fuente_financ
    id:
        anoEje:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ano_eje
        fuenteFinanc:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
            id: true
            column: fuente_financ
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        origen:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
        estado:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
    lifecycleCallbacks: {  }
