PlanillaBundle\Entity\Funcion:
    type: entity
    table: funcion
    id:
        anoEje:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ano_eje
        funcion:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
            id: true
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        estado:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
        ambito:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
        esPresupu:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: es_presupu
    lifecycleCallbacks: {  }
