PlanillaBundle\Entity\Funcion:
    type: entity
    table: funcion
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        anoEje:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: ano_eje
        funcion:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
        esPresupu:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
            column: es_presupu
    lifecycleCallbacks: {  }
