PlanillaBundle\Entity\Grpf:
    type: entity
    repositoryClass: PlanillaBundle\Repository\GrpfRepository
    table: grpf
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        anoEje:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: ano_eje
        grpf:
            type: string
            nullable: false
            length: 4
            options:
                fixed: true
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: true
        esPresupu:
            type: boolean
            nullable: true
            column: es_presupu
    lifecycleCallbacks: {  }
