PlanillaBundle\Entity\Meta:
    type: entity
    table: meta
    indexes:
        fk_meta_ejecutora1_idx:
            columns:
                - ejecutora_id
        fk_meta_funcion1_idx:
            columns:
                - funcion_id
        fk_meta_programa1_idx:
            columns:
                - programa_id
        fk_meta_producto1_idx:
            columns:
                - producto_id
        fk_meta_act_proy1_idx:
            columns:
                - act_proy_id
        fk_meta_divfunc1_idx:
            columns:
                - divfunc_id
        fk_meta_grpf1_idx:
            columns:
                - grpf_id
    id:
        secFunc:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: sec_func
            generator:
                strategy: IDENTITY
    fields:
        meta:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        finalidad:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
    manyToOne:
        actProy:
            targetEntity: ActProy
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                act_proy_id:
                    referencedColumnName: id
            orphanRemoval: false
        divfunc:
            targetEntity: Divfunc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                divfunc_id:
                    referencedColumnName: id
            orphanRemoval: false
        ejecutora:
            targetEntity: Ejecutora
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ejecutora_id:
                    referencedColumnName: id
            orphanRemoval: false
        funcion:
            targetEntity: Funcion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                funcion_id:
                    referencedColumnName: id
            orphanRemoval: false
        grpf:
            targetEntity: Grpf
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                grpf_id:
                    referencedColumnName: id
            orphanRemoval: false
        producto:
            targetEntity: Producto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                producto_id:
                    referencedColumnName: id
            orphanRemoval: false
        programa:
            targetEntity: Programa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                programa_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
