PlanillaBundle\Entity\Personal:
    type: entity
    table: personal
    indexes:
        fk_personal_sexo1_idx:
            columns:
                - sexo
        fk_personal_tipo_doc1_idx:
            columns:
                - tipo_doc
    id:
        codPersonal:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: cod_personal
            generator:
                strategy: IDENTITY
    fields:
        apellidoPaterno:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: apellido_paterno
        apellidoMaterno:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: apellido_materno
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        anexo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        fechaNacimiento:
            type: date
            nullable: true
            column: fecha_nacimiento
        numeroDocumento:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: numero_documento
        cuspp:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        numAutogenerado:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: num_autogenerado
        estado:
            type: boolean
            nullable: false
    manyToOne:
        sexo:
            targetEntity: Sexo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sexo:
                    referencedColumnName: id
            orphanRemoval: false
        tipoDoc:
            targetEntity: TipoDoc
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_doc:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
