PlanillaBundle\Entity\PlazaHistorial:
    type: entity
    table: plaza_historial
    indexes:
        fk_plaza_historial_personal1_idx:
            columns:
                - cod_personal
        fk_plaza_historial_afp1_idx:
            columns:
                - afp
        fk_plaza_historial_modo_ingreso1_idx:
            columns:
                - modo_ingreso_id
        fk_plaza_historial_unidad1_idx:
            columns:
                - unidad_id
        fk_plaza_historial_plaza1_idx1:
            columns:
                - plaza_id
        fk_plaza_historial_situacion_laboral1_idx:
            columns:
                - situacion_laboral_id
        fk_plaza_historial_regimen_pensionario1_idx:
            columns:
                - regimen_pensionario_id
        fk_plaza_historial_regimen_laboral1_idx:
            columns:
                - regimen_laboral_id
        fk_plaza_historial_condicion_laboral1_idx:
            columns:
                - condicion_laboral
        fk_plaza_historial_motivo_anulacion1_idx:
            columns:
                - motivo_anulacion_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        secPersonal:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: sec_personal
        fechaIngreso:
            type: date
            nullable: true
            column: fecha_ingreso
        fechaCese:
            type: date
            nullable: true
            column: fecha_cese
        resolucion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        fechaAnulacion:
            type: date
            nullable: true
            column: fecha_anulacion
        cargo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        fechaAfp:
            type: date
            nullable: true
            column: fecha_afp
        estado:
            type: boolean
            nullable: true
        docAnulacion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: doc_anulacion
        afpMix:
            type: boolean
            nullable: true
            column: afp_mix
    manyToOne:
        afp:
            targetEntity: Afp
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                afp:
                    referencedColumnName: id
            orphanRemoval: false
        condicionLaboral:
            targetEntity: CondicionLaboral
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                condicion_laboral:
                    referencedColumnName: id
            orphanRemoval: false
        modoIngreso:
            targetEntity: ModoIngreso
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                modo_ingreso_id:
                    referencedColumnName: id
            orphanRemoval: false
        motivoAnulacion:
            targetEntity: MotivoAnulacion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                motivo_anulacion_id:
                    referencedColumnName: id
            orphanRemoval: false
        codPersonal:
            targetEntity: Personal
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_personal:
                    referencedColumnName: cod_personal
            orphanRemoval: false
        plaza:
            targetEntity: Plaza
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: plazaHistorial
            joinColumns:
                plaza_id:
                    referencedColumnName: id
            orphanRemoval: false
        regimenLaboral:
            targetEntity: RegimenLaboral
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                regimen_laboral_id:
                    referencedColumnName: id
            orphanRemoval: false
        regimenPensionario:
            targetEntity: RegimenPensionario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                regimen_pensionario_id:
                    referencedColumnName: id
            orphanRemoval: false
        situacionLaboral:
            targetEntity: SituacionLaboral
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                situacion_laboral_id:
                    referencedColumnName: id
            orphanRemoval: false
        unidad:
            targetEntity: Unidad
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                unidad_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
