PlanillaBundle\Entity\Plaza:
    type: entity
    table: plaza
    indexes:
        fk_plaza_meta1_idx:
            columns:
                - sec_func
        fk_plaza_categoria_ocupacional1_idx:
            columns:
                - categoria_id
        fk_plaza_tipo_planilla1_idx:
            columns:
                - tipo_planilla
        fk_plaza_especifica1_idx:
            columns:
                - especifica_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numPlaza:
            type: string
            nullable: false
            length: 6
            options:
                fixed: true
            column: num_plaza
        estado:
            type: boolean
            nullable: false
    manyToOne:
        categoria:
            targetEntity: CategoriaOcupacional
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                categoria_id:
                    referencedColumnName: id
            orphanRemoval: false
        especifica:
            targetEntity: Especifica
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                especifica_id:
                    referencedColumnName: id
            orphanRemoval: false
        secFunc:
            targetEntity: Meta
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sec_func:
                    referencedColumnName: sec_func
            orphanRemoval: false
        tipoPlanilla:
            targetEntity: TipoPlanilla
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_planilla:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        plazaHistorial:
            targetEntity: PlazaHistorial
            mappedBy: plaza
    lifecycleCallbacks: {  }
