PlanillaBundle\Entity\Plaza:
    type: entity
    table: plaza
    indexes:
        fk_plaza_categoria_ocupacional1_idx:
            columns:
                - grupo_ocupacional
                - categoria_ocupacional
        fk_plaza_meta1_idx:
            columns:
                - sec_func
    id:
        tipoPlanilla:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
            id: true
            column: tipo_planilla
        numPlaza:
            type: string
            nullable: false
            length: 6
            options:
                fixed: true
            id: true
            column: num_plaza
    fields:
        estado:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
                default: A
        especifica:
            type: string
            nullable: true
            length: 10
            options:
                fixed: true
    manyToOne:
        grupoOcupacional:
            targetEntity: CategoriaOcupacional
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                grupo_ocupacional:
                    referencedColumnName: grupo_ocupacional
                categoria_ocupacional:
                    referencedColumnName: categoria_ocupacional
            orphanRemoval: false
        secFunc:
            targetEntity: Meta
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sec_func:
                    referencedColumnName: sec_func
            orphanRemoval: false
    lifecycleCallbacks: {  }
