PlanillaBundle\Entity\Pliego:
    type: entity
    table: pliego
    indexes:
        fk_pliego_sector1_idx:
            columns:
                - sector_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pliego:
            type: string
            nullable: false
            length: 3
            options:
                fixed: true
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
    manyToOne:
        sector:
            targetEntity: Sector
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sector_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
