PlanillaBundle\Entity\Pliego:
    type: entity
    table: pliego
    indexes:
        fk_pliego_sector1:
            columns:
                - ano_eje
                - sector
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pliego:
            type: string
            nullable: false
            length: 3
            options:
                fixed: true
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        estado:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
        regional:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
    manyToOne:
        anoEje:
            targetEntity: Sector
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ano_eje:
                    referencedColumnName: ano_eje
                sector:
                    referencedColumnName: sector
            orphanRemoval: false
    lifecycleCallbacks: {  }
