PlanillaBundle\Entity\Producto:
    type: entity
    table: producto
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        anoEje:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: ano_eje
        producto:
            type: string
            nullable: false
            length: 10
            options:
                fixed: true
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: true
        esPresupu:
            type: boolean
            nullable: true
            column: es_presupu
    lifecycleCallbacks: {  }
