PlanillaBundle\Entity\ProgramacionPagos:
    type: entity
    table: programacion_pagos
    id:
        anoEje:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ano_eje
        mesEje:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: mes_eje
        secEjec:
            type: string
            nullable: false
            length: 6
            options:
                fixed: true
            id: true
            column: sec_ejec
    fields:
        fechaPension:
            type: datetime
            nullable: true
            column: fecha_pension
        fechaActivo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: fecha_activo
    lifecycleCallbacks: {  }
