PlanillaBundle\Entity\RegimenLaboral:
    type: entity
    repositoryClass: PlanillaBundle\Repository\RegimenLaboralRepository
    table: regimen_laboral
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
        descripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        sueldoMinimo:
            type: float
            nullable: true
            precision: 15
            scale: 2
            column: sueldo_minimo
    lifecycleCallbacks: {  }
