PlanillaBundle\Entity\RegimenPensionario:
    type: entity
    repositoryClass: PlanillaBundle\Repository\RegimenPensionarioRepository
    table: regimen_pensionario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
