PlanillaBundle\Entity\Sector:
    type: entity
    table: sector
    id:
        anoEje:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ano_eje
        sector:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
            id: true
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        estado:
            type: string
            nullable: true
            length: 1
            options:
                fixed: true
    lifecycleCallbacks: {  }
