PlanillaBundle\Entity\Sector:
    type: entity
    table: sector
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        anoEje:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: ano_eje
        sector:
            type: string
            nullable: false
            length: 2
            options:
                fixed: true
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
