PlanillaBundle\Entity\TipoPlanilla:
    type: entity
    table: tipo_planilla
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
