PlanillaBundle\Entity\Usuario:
    type: entity
    table: usuario
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dni:
            type: string
            nullable: false
            length: 8
            options:
                fixed: true
        apellidos:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nombres:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        cargo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nick:
            type: string
            nullable: false
            length: 10
            options:
                fixed: true
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
        role:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        claveapi:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    oneToMany:
        planilla:
            targetEntity: Planilla
            mappedBy: usuario 
    lifecycleCallbacks: {  }
