PlanillaBundle\Entity\Usuario:
    type: entity
    table: usuario
    id:
        dni:
            type: string
            nullable: false
            length: 8
            options:
                fixed: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        apellidos:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        nombres:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        cargo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        nick:
            type: string
            nullable: false
            length: 100
            options:
                fixed: true
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        estado:
            type: boolean
            nullable: false
            options:
                default: '1'
        claveapi:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        role:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
