login:
    path: /login
    defaults: { _controller: PlanillaBundle:Usuario:login }
    
logout:
    path: /logout
    
planilla_homepage:
    path: /
    defaults: { _controller: PlanillaBundle:Default:index }
    
usuario_index:
    path: /usuario/index
    defaults: { _controller: PlanillaBundle:Usuario:index }
    
usuario_add:
    path: /usuario/add
    defaults: { _controller: PlanillaBundle:Usuario:add }
    
usuario_edit:
    path: /usuario/edit/{id}
    defaults: { _controller: PlanillaBundle:Usuario:edit }
    
usuario_delete:
    path: /usuario/delete/{id}
    defaults: { _controller: PlanillaBundle:Usuario:delete }
    
concepto_index:
    path: /concepto/index
    defaults: { _controller: PlanillaBundle:Concepto:index }
    
concepto_add:
    path: /concepto/add
    defaults: { _controller: PlanillaBundle:Concepto:add }
    
concepto_edit:
    path: /concepto/edit/{id}
    defaults: { _controller: PlanillaBundle:Concepto:edit }
    
personal_index:
    path: /personal/index
    defaults: { _controller: PlanillaBundle:Personal:index }
    
personal_add:
    path: /personal/add
    defaults: { _controller: PlanillaBundle:Personal:add }
    
personal_edit:
    path: /personal/edit/{codPersonal}
    defaults: { _controller: PlanillaBundle:Personal:edit }
    
plaza_index:
    path: /plaza/index
    defaults: { _controller: PlanillaBundle:Plaza:index }

plaza_add:
    path: /plaza/add/
    defaults: { _controller: PlanillaBundle:Plaza:add }
    
plaza_edit:
    path: /plaza/edit/{id}
    defaults: { _controller: PlanillaBundle:Plaza:edit }
    
plaza_ajax_numPlaza:
    path:     /plaza/numPlaza
    defaults: { _controller: "PlanillaBundle:Plaza:modifyNumPlaza" }
    methods:  GET
    
plaza_ajax_categoria:
    path:     /plaza/categoria
    defaults: { _controller: "PlanillaBundle:Plaza:modifyCategoria" }
    methods:  GET
    
especifica_index:
    path: /especifica/index
    defaults: { _controller: PlanillaBundle:Especifica:index }
    
especifica_add:
    path: /especifica/add
    defaults: { _controller: PlanillaBundle:Especifica:add }
    
especifica_edit:
    path: /especifica/edit/{id}
    defaults: { _controller: PlanillaBundle:Especifica:edit }
    
fuente_index:
    path: /fuente/index
    defaults: { _controller: PlanillaBundle:FuenteFinanc:index }
    
fuente_add:
    path: /fuente/add
    defaults: { _controller: PlanillaBundle:FuenteFinanc:add }
    
fuente_edit:
    path: /fuente/edit/{id}
    defaults: { _controller: PlanillaBundle:FuenteFinanc:edit }
    
sector_index:
    path: /sector/index
    defaults: { _controller: PlanillaBundle:Sector:index }
    
sector_add:
    path: /sector/add
    defaults: { _controller: PlanillaBundle:Sector:add }
    
sector_edit:
    path: /sector/edit/{id}
    defaults: { _controller: PlanillaBundle:Sector:edit }
    
pliego_index:
    path: /pliego/index
    defaults: { _controller: PlanillaBundle:Pliego:index }
    
pliego_add:
    path: /pliego/add
    defaults: { _controller: PlanillaBundle:Pliego:add }
    
pliego_edit:
    path: /pliego/edit/{id}
    defaults: { _controller: PlanillaBundle:Pliego:edit }
    
ejecutora_index:
    path: /ejecutora/index
    defaults: { _controller: PlanillaBundle:Ejecutora:index }
    
ejecutora_add:
    path: /ejecutora/add
    defaults: { _controller: PlanillaBundle:Ejecutora:add }
    
ejecutora_edit:
    path: /ejecutora/edit/{id}
    defaults: { _controller: PlanillaBundle:Ejecutora:edit }
    
programa_index:
    path: /programa/index
    defaults: { _controller: PlanillaBundle:Programa:index }
    
programa_add:
    path: /programa/add
    defaults: { _controller: PlanillaBundle:Programa:add }
    
programa_edit:
    path: /programa/edit/{id}
    defaults: { _controller: PlanillaBundle:Programa:edit }
    
producto_index:
    path: /producto/index
    defaults: { _controller: PlanillaBundle:Producto:index }
    
producto_add:
    path: /producto/add
    defaults: { _controller: PlanillaBundle:Producto:add }
    
producto_edit:
    path: /producto/edit/{id}
    defaults: { _controller: PlanillaBundle:Producto:edit }
    
actividad_index:
    path: /actividad/index
    defaults: { _controller: PlanillaBundle:ActProy:index }
    
actividad_add:
    path: /actividad/add
    defaults: { _controller: PlanillaBundle:ActProy:add }
    
actividad_edit:
    path: /actividad/edit/{id}
    defaults: { _controller: PlanillaBundle:ActProy:edit }
    
funcion_index:
    path: /funcion/index
    defaults: { _controller: PlanillaBundle:Funcion:index }
    
funcion_add:
    path: /funcion/add
    defaults: { _controller: PlanillaBundle:Funcion:add }
    
funcion_edit:
    path: /funcion/edit/{id}
    defaults: { _controller: PlanillaBundle:Funcion:edit }
    
divfunc_index:
    path: /divfunc/index
    defaults: { _controller: PlanillaBundle:Divfunc:index }
    
divfunc_add:
    path: /divfunc/add
    defaults: { _controller: PlanillaBundle:Divfunc:add }
    
divfunc_edit:
    path: /divfunc/edit/{id}
    defaults: { _controller: PlanillaBundle:Divfunc:edit }
    
grpf_index:
    path: /grpf/index
    defaults: { _controller: PlanillaBundle:Grpf:index }
    
grpf_add:
    path: /grpf/add
    defaults: { _controller: PlanillaBundle:Grpf:add }
    
grpf_edit:
    path: /grpf/edit/{id}
    defaults: { _controller: PlanillaBundle:Grpf:edit }
    
meta_index:
    path: /meta/index
    defaults: { _controller: PlanillaBundle:Meta:index }
    
meta_add:
    path: /meta/add
    defaults: { _controller: PlanillaBundle:Meta:add }
    
meta_edit:
    path: /meta/edit/{id}
    defaults: { _controller: PlanillaBundle:Meta:edit }
    
afp_index:
    path: /afp/index
    defaults: { _controller: PlanillaBundle:Afp:index }
    
afp_add:
    path: /afp/add
    defaults: { _controller: PlanillaBundle:Afp:add }
    
afp_edit:
    path: /afp/edit/{id}
    defaults: { _controller: PlanillaBundle:Afp:edit }
    
regimenPensionario_index:
    path: /regimenPensionario/index
    defaults: { _controller: PlanillaBundle:RegimenPensionario:index }
    
regimenPensionario_add:
    path: /regimenPensionario/add
    defaults: { _controller: PlanillaBundle:RegimenPensionario:add }
    
regimenPensionario_edit:
    path: /regimenPensionario/edit/{id}
    defaults: { _controller: PlanillaBundle:RegimenPensionario:edit }
    
regimenLaboral_index:
    path: /regimenLaboral/index
    defaults: { _controller: PlanillaBundle:RegimenLaboral:index }
    
regimenLaboral_add:
    path: /regimenLaboral/add
    defaults: { _controller: PlanillaBundle:RegimenLaboral:add }
    
regimenLaboral_edit:
    path: /regimenLaboral/edit/{id}
    defaults: { _controller: PlanillaBundle:RegimenLaboral:edit }
    
situacionLaboral_index:
    path: /situacionLaboral/index
    defaults: { _controller: PlanillaBundle:SituacionLaboral:index }
    
situacionLaboral_add:
    path: /situacionLaboral/add
    defaults: { _controller: PlanillaBundle:SituacionLaboral:add }
    
situacionLaboral_edit:
    path: /situacionLaboral/edit/{id}
    defaults: { _controller: PlanillaBundle:SituacionLaboral:edit }

condicionLaboral_index:
    path: /condicionLaboral/index
    defaults: { _controller: PlanillaBundle:CondicionLaboral:index }
    
condicionLaboral_add:
    path: /condicionLaboral/add
    defaults: { _controller: PlanillaBundle:CondicionLaboral:add }
    
condicionLaboral_edit:
    path: /condicionLaboral/edit/{id}
    defaults: { _controller: PlanillaBundle:CondicionLaboral:edit }
    
motivoAnulacion_index:
    path: /motivoAnulacion/index
    defaults: { _controller: PlanillaBundle:MotivoAnulacion:index }
    
motivoAnulacion_add:
    path: /motivoAnulacion/add
    defaults: { _controller: PlanillaBundle:MotivoAnulacion:add }
    
motivoAnulacion_edit:
    path: /motivoAnulacion/edit/{id}
    defaults: { _controller: PlanillaBundle:MotivoAnulacion:edit }
    
tipoDoc_index:
    path: /tipoDoc/index
    defaults: { _controller: PlanillaBundle:TipoDoc:index }
    
tipoDoc_add:
    path: /tipoDoc/add
    defaults: { _controller: PlanillaBundle:TipoDoc:add }
    
tipoDoc_edit:
    path: /tipoDoc/edit/{id}
    defaults: { _controller: PlanillaBundle:TipoDoc:edit }
    
sexo_index:
    path: /sexo/index
    defaults: { _controller: PlanillaBundle:Sexo:index }
    
sexo_add:
    path: /sexo/add
    defaults: { _controller: PlanillaBundle:Sexo:add }
    
sexo_edit:
    path: /sexo/edit/{id}
    defaults: { _controller: PlanillaBundle:Sexo:edit }
    
tipoPlanilla_index:
    path: /tipoPlanilla/index
    defaults: { _controller: PlanillaBundle:TipoPlanilla:index }
    
tipoPlanilla_add:
    path: /tipoPlanilla/add
    defaults: { _controller: PlanillaBundle:TipoPlanilla:add }
    
tipoPlanilla_edit:
    path: /tipoPlanilla/edit/{id}
    defaults: { _controller: PlanillaBundle:TipoPlanilla:edit }
    
tipoConcepto_index:
    path: /tipoConcepto/index
    defaults: { _controller: PlanillaBundle:TipoConcepto:index }
    
tipoConcepto_add:
    path: /tipoConcepto/add
    defaults: { _controller: PlanillaBundle:TipoConcepto:add }
    
tipoConcepto_edit:
    path: /tipoConcepto/edit/{id}
    defaults: { _controller: PlanillaBundle:TipoConcepto:edit }
    
plazaHistorial_index:
    path: /plazaHistorial/index/{id}
    defaults: { _controller: PlanillaBundle:PlazaHistorial:index }

plazaHistorial_add:
    path: /plazaHistorial/add/{plazaId}
    defaults: { _controller: PlanillaBundle:PlazaHistorial:add }
    
plazaHistorial_edit:
    path: /plazaHistorial/edit/{id}
    defaults: { _controller: PlanillaBundle:PlazaHistorial:edit }
    
plazaHistorial_baja:
    path: /plazaHistorial/baja/{id}
    defaults: { _controller: PlanillaBundle:PlazaHistorial:baja }
    
plazaHistorial_ajax_afp:
    path:     /plazaHistorial/afp
    defaults: { _controller: "PlanillaBundle:PlazaHistorial:modifyAfp" }
    methods:  GET
    
grupoOcupacional_index:
    path: /grupoOcupacional/index
    defaults: { _controller: PlanillaBundle:GrupoOcupacional:index }
    
grupoOcupacional_add:
    path: /grupoOcupacional/add
    defaults: { _controller: PlanillaBundle:GrupoOcupacional:add }
    
grupoOcupacional_edit:
    path: /grupoOcupacional/edit/{id}
    defaults: { _controller: PlanillaBundle:GrupoOcupacional:edit }
    
categoriaOcupacional_index:
    path: /categoriaOcupacional/index
    defaults: { _controller: PlanillaBundle:CategoriaOcupacional:index }
    
categoriaOcupacional_add:
    path: /categoriaOcupacional/add
    defaults: { _controller: PlanillaBundle:CategoriaOcupacional:add }
    
categoriaOcupacional_edit:
    path: /categoriaOcupacional/edit/{id}
    defaults: { _controller: PlanillaBundle:CategoriaOcupacional:edit }
    
planilla_index:
    path: /planilla/index
    defaults: { _controller: PlanillaBundle:Planilla:index }
    
planilla_consulta:
    path: /planilla/consulta
    defaults: { _controller: PlanillaBundle:Planilla:consulta }
    
planilla_add:
    path: /planilla/add/
    defaults: { _controller: PlanillaBundle:Planilla:add }
    
planilla_edit:
    path: /planilla/edit/{id}
    defaults: { _controller: PlanillaBundle:Planilla:edit }
    
planilla_delete:
    path: /planilla/delete/{id}
    defaults: { _controller: PlanillaBundle:Planilla:delete }
    
planilla_generacion:
    path: /planilla/generacion
    defaults: { _controller: PlanillaBundle:Planilla:generacion }
    
planilla_fechas:
    path: /planilla/fechas
    defaults: { _controller: PlanillaBundle:Planilla:fechas }
    
planilla_ajax_plazaHistorial:
    path:     /planilla/plazaHistorial
    defaults: { _controller: "PlanillaBundle:Planilla:modifyPlazaHistorial" }
    methods:  GET
    
planillaHasConcepto_index:
    path: /planillaHasConcepto/index/{planillaId}
    defaults: { _controller: PlanillaBundle:PlanillaHasConcepto:index }
    
planillaHasConcepto_consulta:
    path: /planillaHasConcepto/consulta/{planillaId}
    defaults: { _controller: PlanillaBundle:PlanillaHasConcepto:consulta }
    
planillaHasConcepto_add:
    path: /planillaHasConcepto/add/{planillaId}
    defaults: { _controller: PlanillaBundle:PlanillaHasConcepto:add }
    
planillaHasConcepto_edit:
    path: /planillaHasConcepto/edit/{id}
    defaults: { _controller: PlanillaBundle:PlanillaHasConcepto:edit }
    
planillaHasConcepto_tardanzas:
    path: /planillaHasConcepto/tardanzas/{planillaId}
    defaults: { _controller: PlanillaBundle:PlanillaHasConcepto:tardanzas }

planillaHasConcepto_delete:
    path: /planillaHasConcepto/delete/{id}
    defaults: { _controller: PlanillaBundle:PlanillaHasConcepto:delete }
    
planillaHasConcepto_ajax_concepto:
    path:     /planillaHasConcepto/concepto
    defaults: { _controller: "PlanillaBundle:PlanillaHasConcepto:modifyConcepto" }
    methods:  GET