login:
    path: /login
    defaults: { _controller: PlanillaBundle:Usuario:login }
    
logout:
    path: /logout
    
planilla_homepage:
    path: /
    defaults: { _controller: PlanillaBundle:Default:index }
    
usuario_index:
    path: /usuario/index
    defaults: { _controller: PlanillaBundle:Usuario:index }
    
usuario_add:
    path: /usuario/add
    defaults: { _controller: PlanillaBundle:Usuario:add }
    
usuario_edit:
    path: /usuario/edit/{id}
    defaults: { _controller: PlanillaBundle:Usuario:edit }
    
usuario_delete:
    path: /usuario/delete/{id}
    defaults: { _controller: PlanillaBundle:Usuario:delete }
    
concepto_index:
    path: /concepto/index
    defaults: { _controller: PlanillaBundle:Concepto:index }
    
concepto_add:
    path: /concepto/add
    defaults: { _controller: PlanillaBundle:Concepto:add }
    
concepto_edit:
    path: /concepto/edit/{id}
    defaults: { _controller: PlanillaBundle:Concepto:edit }
    
personal_index:
    path: /personal/index
    defaults: { _controller: PlanillaBundle:Personal:index }
    
personal_add:
    path: /personal/add
    defaults: { _controller: PlanillaBundle:Personal:add }
    
personal_edit:
    path: /personal/edit/{codPersonal}
    defaults: { _controller: PlanillaBundle:Personal:edit }
