login:
    path: /login
    defaults: { _controller: PlanillaBundle:Usuario:login }
    
logout:
    path: /logout
    
planilla_homepage:
    path: /
    defaults: { _controller: PlanillaBundle:Default:index }
    
usuario_index:
    path: /usuario/index
    defaults: { _controller: PlanillaBundle:Usuario:index }
    
usuario_add:
    path: /usuario/add
    defaults: { _controller: PlanillaBundle:Usuario:add }
    
usuario_edit:
    path: /usuario/edit/{id}
    defaults: { _controller: PlanillaBundle:Usuario:edit }
    
usuario_delete:
    path: /usuario/delete/{id}
    defaults: { _controller: PlanillaBundle:Usuario:delete }
    
concepto_index:
    path: /concepto/index
    defaults: { _controller: PlanillaBundle:Concepto:index }
    
concepto_add:
    path: /concepto/add
    defaults: { _controller: PlanillaBundle:Concepto:add }
    
concepto_edit:
    path: /concepto/edit/{id}
    defaults: { _controller: PlanillaBundle:Concepto:edit }
    
personal_index:
    path: /personal/index
    defaults: { _controller: PlanillaBundle:Personal:index }
    
personal_add:
    path: /personal/add
    defaults: { _controller: PlanillaBundle:Personal:add }
    
personal_edit:
    path: /personal/edit/{codPersonal}
    defaults: { _controller: PlanillaBundle:Personal:edit }
    
plaza_index:
    path: /plaza/index
    defaults: { _controller: PlanillaBundle:Plaza:index }

plaza_add:
    path: /plaza/add
    defaults: { _controller: PlanillaBundle:Plaza:add }
    
plaza_edit:
    path: /plaza/edit/{id}
    defaults: { _controller: PlanillaBundle:Plaza:edit }
    
especifica_index:
    path: /especifica/index
    defaults: { _controller: PlanillaBundle:Especifica:index }
    
especifica_add:
    path: /especifica/add
    defaults: { _controller: PlanillaBundle:Especifica:add }
    
especifica_edit:
    path: /especifica/edit/{id}
    defaults: { _controller: PlanillaBundle:Especifica:edit }
    
fuente_index:
    path: /fuente/index
    defaults: { _controller: PlanillaBundle:FuenteFinanc:index }
    
fuente_add:
    path: /fuente/add
    defaults: { _controller: PlanillaBundle:FuenteFinanc:add }
    
fuente_edit:
    path: /fuente/edit/{id}
    defaults: { _controller: PlanillaBundle:FuenteFinanc:edit }
    
sector_index:
    path: /sector/index
    defaults: { _controller: PlanillaBundle:Sector:index }
    
sector_add:
    path: /sector/add
    defaults: { _controller: PlanillaBundle:Sector:add }
    
sector_edit:
    path: /sector/edit/{id}
    defaults: { _controller: PlanillaBundle:Sector:edit }
    
pliego_index:
    path: /pliego/index
    defaults: { _controller: PlanillaBundle:Pliego:index }
    
pliego_add:
    path: /pliego/add
    defaults: { _controller: PlanillaBundle:Pliego:add }
    
pliego_edit:
    path: /pliego/edit/{id}
    defaults: { _controller: PlanillaBundle:Pliego:edit }
    
ejecutora_index:
    path: /ejecutora/index
    defaults: { _controller: PlanillaBundle:Ejecutora:index }
    
ejecutora_add:
    path: /ejecutora/add
    defaults: { _controller: PlanillaBundle:Ejecutora:add }
    
ejecutora_edit:
    path: /ejecutora/edit/{id}
    defaults: { _controller: PlanillaBundle:Ejecutora:edit }
    
programa_index:
    path: /programa/index
    defaults: { _controller: PlanillaBundle:Programa:index }
    
programa_add:
    path: /programa/add
    defaults: { _controller: PlanillaBundle:Programa:add }
    
programa_edit:
    path: /programa/edit/{id}
    defaults: { _controller: PlanillaBundle:Programa:edit }
    
producto_index:
    path: /producto/index
    defaults: { _controller: PlanillaBundle:Producto:index }
    
producto_add:
    path: /producto/add
    defaults: { _controller: PlanillaBundle:Producto:add }
    
producto_edit:
    path: /producto/edit/{id}
    defaults: { _controller: PlanillaBundle:Producto:edit }
    
actividad_index:
    path: /actividad/index
    defaults: { _controller: PlanillaBundle:ActProy:index }
    
actividad_add:
    path: /actividad/add
    defaults: { _controller: PlanillaBundle:ActProy:add }
    
actividad_edit:
    path: /actividad/edit/{id}
    defaults: { _controller: PlanillaBundle:ActProy:edit }
    
funcion_index:
    path: /funcion/index
    defaults: { _controller: PlanillaBundle:Funcion:index }
    
funcion_add:
    path: /funcion/add
    defaults: { _controller: PlanillaBundle:Funcion:add }
    
funcion_edit:
    path: /funcion/edit/{id}
    defaults: { _controller: PlanillaBundle:Funcion:edit }
    
divfunc_index:
    path: /divfunc/index
    defaults: { _controller: PlanillaBundle:Divfunc:index }
    
divfunc_add:
    path: /divfunc/add
    defaults: { _controller: PlanillaBundle:Divfunc:add }
    
divfunc_edit:
    path: /divfunc/edit/{id}
    defaults: { _controller: PlanillaBundle:Divfunc:edit }
    
grpf_index:
    path: /grpf/index
    defaults: { _controller: PlanillaBundle:Grpf:index }
    
grpf_add:
    path: /grpf/add
    defaults: { _controller: PlanillaBundle:Grpf:add }
    
grpf_edit:
    path: /grpf/edit/{id}
    defaults: { _controller: PlanillaBundle:Grpf:edit }
    
meta_index:
    path: /meta/index
    defaults: { _controller: PlanillaBundle:Meta:index }
    
meta_add:
    path: /meta/add
    defaults: { _controller: PlanillaBundle:Meta:add }
    
meta_edit:
    path: /meta/edit/{id}
    defaults: { _controller: PlanillaBundle:Meta:edit }